# Generated by Django 2.0.2 on 2018-02-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='exit', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
